version: '3.4'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    volumes:
      - jenkins_volume:/var/jenkins_home
    ports:
      - 3000:8080
  ssh-server:
    image: ubuntu-ssh-server
    build:
      context: .
      dockerfile: ./docker-images/Dockerfile-ssh-server
    ports:
      - "3022:22"
volumes:
  jenkins_volume: